# Generated by Django 3.0.1 on 2020-01-01 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nume', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('descriere', models.CharField(blank=True, max_length=255)),
                ('ocupatie', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, default='N', max_length=1)),
                ('varsta', models.PositiveIntegerField(blank=True, null=True)),
                ('buget', models.PositiveIntegerField(null=True)),
                ('imagine_profil', models.ImageField(blank=True, upload_to='utilizatori/')),
                ('cont_premium', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Utilizatori',
            },
        ),
        migrations.CreateModel(
            name='Anunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_postarii', models.DateTimeField(auto_now_add=True)),
                ('localitate', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=100)),
                ('pret', models.PositiveIntegerField()),
                ('numar_camere', models.PositiveIntegerField()),
                ('numar_colegi', models.PositiveIntegerField()),
                ('mfx', models.CharField(max_length=1)),
                ('descriere', models.TextField(max_length=250)),
                ('img1', models.ImageField(upload_to='anunturi/')),
                ('img2', models.ImageField(blank=True, upload_to='anunturi/')),
                ('img3', models.ImageField(blank=True, upload_to='anunturi/')),
                ('img4', models.ImageField(blank=True, upload_to='anunturi/')),
                ('img5', models.ImageField(blank=True, upload_to='anunturi/')),
                ('img6', models.ImageField(blank=True, upload_to='anunturi/')),
                ('titlu', models.CharField(blank=True, max_length=50)),
                ('facilitati', models.CharField(blank=True, max_length=255)),
                ('postat_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Anunturi',
            },
        ),
        migrations.CreateModel(
            name='Sheriasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Anunt')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sheriasi',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Anunt')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favorite',
            },
        ),
    ]
