# Generated by Django 3.0.1 on 2020-01-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anunt',
            name='titlu',
        ),
        migrations.RemoveField(
            model_name='utilizator',
            name='nume',
        ),
    ]
