# Generated by Django 3.0.1 on 2020-01-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200101_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='token',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
