# Generated by Django 3.0.1 on 2020-01-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_utilizator_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunt',
            name='apartament',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='anunt',
            name='numar_colegi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
