# Generated by Django 3.0.1 on 2020-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200103_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunt',
            name='apartament',
            field=models.BooleanField(),
        ),
    ]
