# Generated by Django 3.0.1 on 2020-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200118_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='nume',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
