# Generated by Django 3.0.1 on 2020-01-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_utilizator_nume'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='telefon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
