# Generated by Django 3.0.1 on 2020-01-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_utilizator_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizator',
            name='imagine_profil',
            field=models.ImageField(blank=True, default='utilizatori/imagine_profil.svg', upload_to='utilizatori/'),
        ),
    ]
