# Generated by Django 3.0.1 on 2020-01-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200118_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anunt',
            old_name='facilitati',
            new_name='alte_detalii',
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='ocupatie',
            field=models.CharField(blank=True, default='nespecificat', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='telefon',
            field=models.CharField(blank=True, default='nespecificat', max_length=20),
        ),
    ]
